<?php
/** 
* cms.config.php
*
* @package      	photonicCMS
* 
*/

if (!defined('PHOTONICCMS')) exit();

return array(
    'id' => 1,
    'programe_name' => '萬用商業版總管理',
    'company_name' => '萬用後台',
    'best_explorer' => '您的瀏覽器必須支援 Cookie 安全機制，並且建議使用IE 8.0或Firefox/3.6.16之版本及 1024 x 768 或以上的解析度瀏覽。',
    'company_logo' => 'Config/201601/logo.png',
    'logo_alt' => 'company logo',
    'logo_url' => 'http://localhost/photonic_cms/',
    'company_pic' => 'Config/201606/logo.png',
    'pic_alt' => 'company picture',
    'pic_url' => 'http://localhost/photonic_cms/',
    'photonic_logo' => 'Images/logo.png',
    'photonic_alt' => 'photonic logo',
    'photonic_url' => 'http://www.photonic.com.tw',
    'photonic_link' => '<LI><A href=\"http://www.photonic.com.tw\">www.photonic.com.tw</A></LI>',
    'contact_name' => 'photonic',
    'telephone' => '',
    'email' => 'planner@photonic.com.tw',
    'fax' => '',
    'mobile_telephone' => '',
    'address' => '',
    'icp' => '',
    'qq' => '',
    'msn' => '',
    'im' => '',
    'web_status' => 1,
    'status_description' => '',
    'header_content' => '',
    'footer_content' => '',
    'download_suffix' => 'Winndows',
    'global_thumb_status' => 1,
    'global_attach_size' => 20480000,
    'global_attach_suffix' => '',
    'product_thumb_status' => 0,
    'product_thumb_size' => '',
    'download_thumb_status' => 0,
    'download_thumb_size' => '',
    'global_thumb_size' => '',
    'seo_title' => '',
    'seo_keyword' => '',
    'seo_description' => '',
    'verify' => 0,
    'hascontact' => 2,
    'online' => 0,
    'hasad' => 1,
    'hasnews' => 2,
    'newstitlelen' => 20,
    'hasmarquee' => 0,
    'marqueecontent' => 'dgaasfd',
    'hasdownload' => 1,
    'downloadsize' => 2048000,
    'haslink' => 1,
    'hasguestbook' => 0,
    'guestbooktitle' => '留言板',
    'hasproject' => 1,
    'hasmobimg' => 1,
    'hasad2' => 1,
    'hasmarquee2' => 0,
    'hasmobimg2' => 1,
    'hasproduct' => 3,
    'hascart' => 1,
    'hascartstatus' => 1,
    'hasmovie' => 1,
    'hasarticle' => 1,
    'hasmanage' => 1,
    'hasvip' => 1,
    'multilan' => 1,
    'contacttitle' => '回函表',
    'contactname' => '萬用後台',
    'istopnum' => 6,
    'recommendnum' => 6,
    'wholefee' => 1000,
    'wholefeenum' => 2424,
    'retailfee' => '',
    'retailfeenum' => 400,
    'salepricetype' => 3,
    'create_time' => 0,
    'update_time' => 0,
);